import type { NextPage } from 'next';
import Head from 'next/head';

const Listing: NextPage = () => {
  return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                  content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Listing</h1>
        </>
  )
}

export default Listing;
